import { executeAllModels } from "@/lib/services/generateResponses";
import { evaluateResponsesStream } from "@/lib/ai/evaluator";

export async function POST(req: Request) {
  try {
    const { prompt } = await req.json();

    if (!prompt || typeof prompt !== "string") {
      return new Response(JSON.stringify({ error: "A valid prompt string is required." }), {
        status: 400,
        headers: { "Content-Type": "application/json" },
      });
    }

    // Step 1: Execute OpenAI, Grok, and Gemini concurrently
    const rawResponses = await executeAllModels(prompt);

    // Step 2: Create a custom ReadableStream (NDJSON) to send models first, then text tokens
    const stream = new ReadableStream({
      async start(controller) {
        try {
          const encoder = new TextEncoder();
          
          // Emit the initial payload with the raw model responses immediately
          const initialPayload = JSON.stringify({ type: "models", data: rawResponses }) + "\n";
          controller.enqueue(encoder.encode(initialPayload));

          // Step 3: Initialize streaming evaluation with Claude
          const textStream = await evaluateResponsesStream({ prompt, responses: rawResponses });

          // Stream the text tokens as they are generated by Claude
          for await (const chunk of textStream) {
            const tokenPayload = JSON.stringify({ type: "text", data: chunk.choices[0]?.delta?.content || "" }) + "\n";
            controller.enqueue(encoder.encode(tokenPayload));
          }
        } catch (err: unknown) {
          console.error("Stream error in route.ts:", err);
          // If streaming fails midway, emit an error block
          const errorMessage = err instanceof Error ? err.message : String(err);
          const errorPayload = JSON.stringify({ type: "error", error: errorMessage }) + "\n";
          controller.enqueue(new TextEncoder().encode(errorPayload));
        } finally {
          controller.close();
        }
      },
    });

    return new Response(stream, {
      headers: {
        "Content-Type": "application/x-ndjson",
        "Cache-Control": "no-cache",
        "Connection": "keep-alive",
      },
    });
  } catch (error: unknown) {
    console.error("Error in generate route:", error);
    const errorMessage = error instanceof Error ? error.message : String(error);
    return new Response(
      JSON.stringify({ error: errorMessage || "An unexpected error occurred." }),
      {
        status: 500,
        headers: { "Content-Type": "application/json" },
      }
    );
  }
}
